name: Multi-Enviornment CI/CD

on:
    push:
        branches:
            - env

jobs:
    test-suite:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Automated Tests
              run: |
                echo "Running unit and integration Tests"
                sleep 3
                echo "Tests Passed"

    onebox:
        runs-on: ubuntu-latest
        steps:
            - name: Depoly to onebox
              run: |
                echo "Deploying to onebox"
                sleep 3
                echo "Deployed to onebox successfully"

    staging:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Staging (Beta/Gamma)
              run: |
                echo "Deploying to Staging Area"
                sleep 3
                echo "Deployed to Staging Area"

    production:
        runs-on: ubuntu-latest
        needs: staging
        steps:
            - name: Deploy yo Production
              run: |
                echo "Deploying to Area"
                sleep 3
                echo "Deployed to Production"
